services:
  telegraf:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-telegraf
    container_name: telegraf-edge
    privileged: true
    pid: "host"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /sys/kernel/debug:/sys/kernel/debug:ro
      - /lib/modules:/lib/modules:ro
      - /usr/src:/usr/src:ro
      - /usr/lib/linux-kbuild-6.1:/usr/lib/linux-kbuild-6.1:ro
    # Lệnh chạy với tham số đi kèm
    command: ["telegraf", "--non-strict-env-handling"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility]