[agent]
  interval = "5s"
  flush_interval = "5s"

[[inputs.execd]]
  command = ["/usr/local/bin/NVML-GPM-Collector"]
  signal = "STDIN"
  data_format = "influx"

[[outputs.file]]
  files = ["stdout"]
  data_format = "json"
