[agent]
  interval = "5s"
  flush_interval = "5s"

[[outputs.http]]
  url = "http://telegraf-bridge:8080"
  method = "POST"
  data_format = "json"
  [outputs.http.headers]
    Content-Type = "application/json"

# -------------------------------------------------------------------
# INPUTS
# -------------------------------------------------------------------
[[inputs.cpu]]
  percpu = false
  totalcpu = true
  fieldpass = ["usage_user", "usage_system", "usage_idle", "usage_iowait"]

[[inputs.diskio]]
  devices = ["nvme0n1"]
  fieldpass = ["io_time", "iops_in_progress", "read_bytes", "reads", "write_bytes", "writes"]

[[inputs.mem]]
  fieldpass = ["used", "available", "total"]
  
[[inputs.processes]]
  fieldpass = ["blocked", "running", "zombies", "idle", "sleeping", "stopped", "total", "total_threads"]

[[inputs.system]]
  fieldpass = ["load1", "load15", "load5", "n_cpus", "uptime"]

# [[inputs.nvidia_smi]]
#   fieldpass = ["temperature_gpu", "utilization_gpu", "utilization_memory", "memory_used", "memory_free", "memory_reserved", "memory_total", "fan_speed"]

# [[inputs.exec]]
#   commands = ["bash -c '/usr/bin/nvidia-smi pmon -c 1 -s u | awk \"NR>2 {print \\$1, \\$2, \\$4, \\$5}\"'"]
#   name_override = "gpu_process_metrics" # Đặt tên chung để merge
#   data_format = "csv"
#   csv_delimiter = " "
#   csv_column_names = ["gpu_idx", "pid", "sm_util", "mem_util"]
#   csv_tag_columns = ["gpu_idx", "pid"]

# [[inputs.exec]]
#   commands = ["/usr/bin/nvidia-smi --query-compute-apps=pid,process_name,used_memory --format=csv,noheader,nounits"]
#   name_override = "gpu_process_metrics" # Đặt tên chung để merge
#   data_format = "csv"
#   csv_column_names = ["pid", "process_name", "used_memory"]
#   csv_tag_columns = ["pid", "process_name"]

# [[inputs.exec]]
#   commands = ["sudo /usr/bin/python3 /opt/telegraf-scripts/tcptop.py 5 1"]
#   name_override = "tcp_top"
#   data_format = "influx"

# -------------------------------------------------------------------
# PROCESSORS & AGGREGATORS
# -------------------------------------------------------------------
[[processors.rename]]
  namepass = ["mem"]
  [[processors.rename.replace]]
    field = "total"
    dest = "mem_total"

[[processors.rename]]
  namepass = ["processes"]
  [[processors.rename.replace]]
    field = "total"
    dest = "proc_total"

[[processors.converter]]
  namepass = ["gpu_process_metrics", "tcp_top"]
  [processors.converter.tags]
    string = ["gpu_idx", "pid", "process_name", "comm", "laddr", "lport", "raddr", "dport"]

[[aggregators.merge]]
  drop_original = true