[agent]
  interval = "5s"
  flush_interval = "5s"
  hostname = "Telegraf-Node-01"

[[outputs.http]]
  url = "http://localhost:8085"
  method = "POST"
  data_format = "json"
  [outputs.http.headers]
    Content-Type = "application/json"

[[inputs.cpu]]
  totalcpu = true
[[inputs.mem]]
[[inputs.net]]
[[inputs.system]]

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "LogicalDisk"
    Instances = ["*"]
    Counters = ["% Free Space", "Disk Read Bytes/sec", "Disk Write Bytes/sec"]
    Measurement = "diskio"

[[inputs.nvidia_smi]]
