{
 "title": "VM-DigitalOcean",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": "import \"influxdata/influxdb/v1\"\r\nv1.tagValues(\r\n    bucket: v.bucket,\r\n    tag: \"host\",\r\n    predicate: (r) => true,\r\n    start: -1d\r\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vm_status\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"result_code\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"VM-Central\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"159.65.138.211\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"VM-DigitalOcean\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"load1\" or r[\"_field\"] == \"load15\" or r[\"_field\"] == \"load5\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Total Memory",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"VM-DigitalOcean\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "System Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"VM-DigitalOcean\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "nCPUs",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "CPUs" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"VM-DigitalOcean\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"n_cpus\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"VM-DigitalOcean\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Total Processes",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"VM-DigitalOcean\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processes\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "query": "from(bucket: \"VM-DigitalOcean\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_system\" or r[\"_field\"] == \"usage_user\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Disk IO - Reads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 13 },
     "targets": [
      {
       "query": "from(bucket: \"VM-DigitalOcean\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"reads\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vda1\" or r[\"name\"] == \"vda\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Disk IO - Writes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 13 },
     "targets": [
      {
       "query": "from(bucket: \"VM-DigitalOcean\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"writes\")\r\n  |> filter(fn: (r) => r[\"name\"] == \"vda1\" or r[\"name\"] == \"vda\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Total Network Received",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"VM-DigitalOcean\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"VM-DigitalOcean\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"eth0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Total Network Sent",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"VM-DigitalOcean\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"VM-DigitalOcean\")\r\n  |> filter(fn: (r) => r[\"interface\"] == \"eth0\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "CPU Distribution",
     "type": "bargauge",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"VM-DigitalOcean\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpudist\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Process-Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage per Process",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Memory Usage per Process",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_percent\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Disk IO Read Bytes per Process",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Disk IO Write Bytes per Process",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"write_bytes\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Network sent (kB/s)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "query": "from(bucket: \"Network-metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net_traffic_v4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"send_kb\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Network received (kB/s)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "query": "from(bucket: \"Network-metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net_traffic_v4\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"recv_kb\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Application-Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usages by Python3 applications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => r[\"app\"] == \"python3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "CPU usages by Telegraf",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"app\"] == \"telegraf\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "CPU usages by Kthreadd application",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"app\"] == \"kthreadd\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Memory Usage by Python3 applications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_percent\")\r\n  |> filter(fn: (r) => r[\"app\"] == \"python3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Memory Usage by Telegraf",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_percent\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"app\"] == \"telegraf\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Memory Usage by Kthreadd application",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mem_percent\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"app\"] == \"kthreadd\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "DiskIO Read Bytes by Python3 applications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\")\r\n  |> filter(fn: (r) => r[\"app\"] == \"python3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "DiskIO Read Bytes by Telegraf",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"app\"] == \"telegraf\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "DiskIO Read Bytes by Kthreadd application",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"app\"] == \"kthreadd\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "DiskIO Write Bytes by Python3 applications",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"write_bytes\")\r\n  |> filter(fn: (r) => r[\"app\"] == \"python3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "DiskIO Write Bytes by Telegraf",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"write_bytes\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"app\"] == \"telegraf\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "DiskIO Write Bytes by Kthreadd application",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"write_bytes\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"app\"] == \"kthreadd\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  },
  {
   "title": "User-Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by Root User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"root\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "CPU Usage by Mysqld User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"mysql\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "DiskIO Write Bytes by Syslog User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"write_bytes\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"syslog\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "CPU Usage by User-1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"user-1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "CPU Usage by User-2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"user-2\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "CPU Usage by User-3",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "query": "from(bucket: \"VM-Central\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hpc-monitoring\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu_percent\")\r\n  |> filter(fn: (r) => r[\"ip\"] == \"159.65.138.211\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"user-3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  }
 ]
}