import os
import json
from airflow import DAG
from datetime import datetime
# Sử dụng Operator mới theo chuẩn GX
from great_expectations_provider.operators.validate_checkpoint import GXValidateCheckpointOperator

# --- CẤU HÌNH ĐƯỜNG DẪN ---
CONFIG_DIR = "/opt/airflow/great_expectations/DQ_layer2/"
GE_ROOT_DIR = "/opt/airflow/great_expectations"
TEST_DATA_DIR = "/opt/airflow/great_expectations/test_data"


def configure_file_data_context():
    import great_expectations as gx

    return gx.get_context(context_root_dir=GE_ROOT_DIR)


def _build_expectations_from_config(config_data):
    import great_expectations.expectations as gxe

    expectations = []

    for rule in config_data.get("table_rules", []):
        if rule.get("rule_name") == "check_table_row_count_not_zero":
            min_value = rule.get("add_info", {}).get("min_value", 1)
            expectations.append(gxe.ExpectTableRowCountToBeBetween(min_value=min_value))

    for col in config_data.get("columns", []):
        col_name = col.get("column_name")
        for dq in col.get("dq_rule(s)", []):
            r_name = dq.get("rule_name")
            if r_name == "check_if_not_null":
                expectations.append(gxe.ExpectColumnValuesToNotBeNull(column=col_name))
            elif r_name == "check_if_values_in_list":
                value_set = dq.get("add_info", {}).get("value_set", [])
                expectations.append(
                    gxe.ExpectColumnValuesToBeInSet(column=col_name, value_set=value_set)
                )

    return expectations


def make_configure_checkpoint(config_data):
    def _configure_checkpoint(context):
        from great_expectations import Checkpoint, ExpectationSuite, ValidationDefinition

        suite_name = config_data.get("validation_definition_name")
        checkpoint_name = config_data.get("checkpoint_name")
        asset_name = config_data.get("data_asset_name")

        datasource = context.data_sources.add_or_update_pandas_filesystem(
            name="my_datasource",
            base_directory=TEST_DATA_DIR,
        )

        try:
            asset = datasource.get_asset(asset_name)
        except Exception:
            asset = datasource.add_csv_asset(
                name=asset_name,
                glob_directive=f"{asset_name}.csv",
            )

        try:
            batch_definition = asset.get_batch_definition("full_table")
        except Exception:
            batch_definition = asset.add_batch_definition(name="full_table")

        # Cleanup legacy suite JSON format generated by previous code.
        legacy_suite_path = os.path.join(GE_ROOT_DIR, "expectations", f"{suite_name}.json")
        if os.path.exists(legacy_suite_path):
            os.remove(legacy_suite_path)

        expectation_suite = context.suites.add_or_update(
            ExpectationSuite(
                name=suite_name,
                expectations=_build_expectations_from_config(config_data),
            )
        )

        validation_definition = context.validation_definitions.add_or_update(
            ValidationDefinition(
                name=f"{suite_name}_vd",
                data=batch_definition,
                suite=expectation_suite,
            )
        )

        checkpoint = Checkpoint(
            name=checkpoint_name,
            validation_definitions=[validation_definition],
            actions=[],
        )
        return context.checkpoints.add_or_update(checkpoint)

    return _configure_checkpoint

# --- KHỞI TẠO DAG ---
with DAG(
    dag_id="dq_layer2_gx_modern",
    schedule="@daily",
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=['gx_core', 'dynamic_tasks']
) as dag:

    # Quét tất cả file JSON trong folder config
    if os.path.exists(CONFIG_DIR):
        for filename in os.listdir(CONFIG_DIR):
            if filename.endswith(".json"):
                with open(os.path.join(CONFIG_DIR, filename), 'r') as f:
                    config = json.load(f)
                
                # SỬ DỤNG OPERATOR MỚI: GXValidateCheckpointOperator
                # Mỗi file JSON tạo ra 1 Task riêng biệt hoàn toàn hiện trên Graph
                GXValidateCheckpointOperator(
                    task_id=f"dq_check_{config['data_asset_name']}",
                    configure_checkpoint=make_configure_checkpoint(config),
                    context_type="file",
                    configure_file_data_context=configure_file_data_context,
                )